### ISSUE TITLE
Third-party license notices - scroll behaviour

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#318] opened 2023-09-10 11:08 UTC
This page only scrolls when mouse is within scroll bar.
With mouse over the text page scrolling doesn't work.

**Comment by trobonox** [comment] 2023-09-10 13:50
On what (sub-)page is this exactly? I thought I had fixed this with 0.5.0 but maybe I forgot a page.

**Comment by PeterP2** [comment] 2023-09-10 14:00
Oh sorry I should have been more precise:
On the side bar click "?" for help
On the page 'Help & Resources' follow the link 'Third-party license notices' at the very bottom

**Comment by trobonox** [comment] 2023-09-10 14:02
On version 0.5.0 on both Windows and macOS, this has been fixed for me after version 0.5.0, so I cannot reproduce this.

**Comment by PeterP2** [comment] 2023-09-10 14:03
Weird, I'm using 0.5.0 from kanri_0.5.0_x64_en-US.msi

**Comment by pnxl** [comment] 2023-09-11 07:20
I can't reproduce this either, can you try/check some of the following things:
* Are you sure you are using the standard Windows Precision drivers? (And not whatever your manufacturer provides)
	* If you are using Windows Precision drivers, try updating Windows (or the drivers)
	* If you are using a third party driver (like something from Elan or Synaptics), try updating those drivers, and if the issue persists you may want to contact them.
	* If do not know, you may have to ask your manufacturer.
* Made sure that you are using 0.5.0, and not an older version
* What is your trackpad? (if you know)
* Reinstall Kanri?

**Comment by PeterP2** [comment] 2023-09-11 11:07
Thanks for your ideas.

I've just connected an external mouse with same result: problem exists but only on this single page.
So I don't think it's a driver problem (which would probably lead to problems on many pages/other software).

I have also reinstalled kanri - by the way "repair" is not possible (greyed out) so I had to uninstall and reinstall again.

Same behaviour as before, this page (see screenshot above) is not scrollable, except when mouse is over the scrollbar.

Win 10 Pro, 22H2, 19045.3393
(all windows updates/driver updates are installed)

I will try a different machine in the evening.

**Comment by PeterP2** [comment] 2023-09-11 18:44
Finally I confirm 'can't reproduce' (any-more).
can be closed I think

But before more strange behaviour occurred (noted just for documentation purposes):

2nd machine everything scrolls fine (like pnxl confirmed)

**Back to laptop:**
on the page mentioned there are two more links:
button 'More JavaScript dependencies (incl.....': subpage scrolls fine
button 'Rust dependencies' subpage does NOT scroll

Connected a different mouse: same behaviour as with first mouse, same behaviour as with internal touchpad
so in total 2 pages won't scroll

**2nd step:**
When I start scrolling while the page loads, I can scroll for about 1 second (works with touchpad or mouse identically)
It seems like after loading the page is finished the focus goes to another element (which has no scroll function)?

This was 100% reproducible also with closing kanri, uninstalling, re-installing kanri, rebooting.

**3rd step:**
Then I started pressing CTRL or ALT while scrolling and it started to work/scroll.
ALT key gets locked/unlocked alternatively each time pressed (which you can see in many apps when underlined characters appear/disappear in menu bar).
When ALT is locked, you can't scroll within kanri (which you can in word e.g.).

After this CTRL/ALT experiments now everything seems to be alright. So scrolling is impossible after pressing ALT once (so ALT is locked) and again scrolling is possible after second time pressing ALT which is fine.

Every time when I enter a page/subpage now, ALT gets correctly unlocked (when pressed ALT once, before clicking a button).

When I now start kanri, all pages scroll fine without the need to unlock ALT key.


Before that third step It seems like ALT key state was saved with the page in cache somewhere? Makes no sense to me either - sorry, but that how it seemed.

Does the app use any pre-installed components?
Edge? Javascript?

Just to know: is any setting different concerning scrolling of those two pages compared to all other pages?
...but only out of curiosity, not really necessary to invest time here.

**Comment by trobonox** [comment] 2023-09-11 19:24
Alright, closing this then.
I'm not sure why the pages would differ, but maybe it's some oversight in the layouts since they are created a little differently (main licenses page is just plain text wrapped in a <pre> tag while the rust licenses are generated html using a tool).
Not a big deal so unless someone else complains I won't spend much time on this.

For external components, Tauri does rely on your system's preinstalled webview, which on Windows is Edge WebView2.

**Closed** 2023-09-11 19:24 UTC
Labels: bug, help wanted, can't reproduce
