### ISSUE TITLE
Refreshing with F5 deletes unsaved cards

### ISSUE THREAD

**Issue by Rostezkiy** [trobonox/kanri#587] opened 2024-06-20 13:17 UTC
**Description**
Refreshing board with F5 deletes unsaved cards

**To Reproduce**
1. Open board with created column
2. Press 'Add card' button and input some text
3. Press F5 to reload the page

**Actual result**
Card disappeared

**Expected behavior**
Probably, it should stay in the same state of creating or be created

**Video**
https://github.com/trobonox/kanri/assets/73363254/da6a0113-abf0-4437-b964-54ca540b18c4

**Desktop**
Kanri 0.7.0
Windows 10, 64bit

**Comment by trobonox** [comment] 2024-06-20 13:54
Refreshing is not supported nor intended behaviour, cards take a while to be saved (and the underlying library to persist them only does periodical saves). This is not in my hands to fix and at most I can try to disable refreshes inside the board view.

**Comment by trobonox** [comment] 2024-06-21 07:10
Disabled just the keyboard shortcut for now, by right clicking anywhere the refresh is still accessible. (and there is also a hidden button which triggers a refresh of the app)

**Comment by trobonox** [comment] 2024-06-24 14:27
Closing because a "fix" is implemented with the latest release.

**Closed by trobonox** 2024-06-24 14:27 UTC
Labels: enhancement
