### ISSUE TITLE
Unable to actually rename a board and the UI errors related to it

### ISSUE THREAD

**Issue by dhugo0022** [trobonox/kanri#215] opened 2023-05-26 14:45 UTC
I just installed Kanri and went to try its features, but I bumped on an error on one of my first tries.

I created a board, but I did a typo on its name, so I went to rename it, and it works at first glance, but when tried to enter the board, its cards weren't present, then I left back to the board list by clicking the Home button, and all the boards just disappears from the board list. I've tried to change views, but didn't have any success... Futhermore, I even tried to close and re-open the app, but the board's new name ins't even set.

P.S: I did a few more tests, and this whole thing only occurs when I try to rename a board. Even when I try to delete a board, after renaming another, it doesn't work. So I guess that the rename logic is the culprit here...

Steps:
- Create a new board with an arbitrary name
- Rename it
- Enter the board (You will soon see that its cards won't appear)
- Click the Home button (By this point, the boards will not be present)

Kanri:
- Version: 0.4.1
- Package: "kanri_0.4.1_amd64.deb"

My system:
- OS: Linux Mint 21.1 x86_64
- Kernel: 5.15.0-70-generic
- Shell: bash 5.1.16
- DE: Cinnamon 5.6.8
- WM: Mutter (Muffin)

**Comment by trobonox** [comment] 2023-05-27 06:52
Thank you for reporting this bug and I apologize for the inconvenience.

I am currently on holidays without any way to test or fix this. As soon as I am back, I will test this and report back if I am able to reproduce the issue.

My current theories are that this is either some kind of Linux-specific bug or something which was introduced with the last patch.
Will test this out and report back soon.

**Comment by trobonox** [comment] 2023-05-28 19:35
I have not been able to reproduce this bug myself on Windows, but I have asked another Linux user and they are experiencing the same issue. This seems to be a Linux-specific issue with the data save logic introduced with the latest patch.
A temporary fix would be to use version 0.4.0, but I will also publish 0.4.2 soon which reverts this new logic to ensure full compatibility with Linux again.

**Comment by dhugo0022** [comment] 2023-05-28 19:42
I see, tysm for help.

**Comment by trobonox** [comment] 2023-05-30 11:39
Just published the 0.4.2 release which should hopefully fix this issue.
If it's not fixed, feel free to reopen this issue.

**Comment by dhugo0022** [comment] 2023-05-30 16:32
Sorry to bring you this news, but the bug still happens... If I had some knowledge with Vue I would most definitely try to help, but I only know React.

**Comment by trobonox** [comment] 2023-05-30 21:55
Very weird, I guess I'll create myself a Debian VM to test this out myself. Seems to be some weird edge case related to tauri-plugin-store which is what I use for persistent storage.

**Comment by trobonox** [comment] 2023-07-16 08:07
I apologize for the long wait, but the issue should finally be fixed with the latest release. Would you mind checking and close the issue if it all works for you now?
Also if in the end you can use the app fine, I would really appreciate a star on GitHub :)

**Comment by trobonox** [comment] 2023-07-19 12:45
I have tested this on multiple configurations and the bug seems to be resolved, so I'm closing this issue.

**Closed** 2023-07-19 12:46 UTC
Labels: bug
