### ISSUE TITLE
Bug: Application refuses to open on M1 Mac

### ISSUE THREAD

**Issue by BhaveshDiwan** [trobonox/kanri#288] opened 2023-08-31 15:02 UTC
I recently did 2 changes together, so this might perhaps be a hisenbug - but it is persistent on my machine.

A few days ago upgraded to latest Ventura from one version behind. Previously installed Kanri (0.4.3) was launching just fine, but performance started degrading slowly over several hours. Another change I then introduced was to test homebrew install (works fine)... The downloaded application wasn't opening unless `xattr -cr` was used.

Now application started taking several minutes to launch. Also tried to export full data in json file which took ~5 minutes as compared to 1 sec previously.

A day after, application outright refuses to load even after hours. Tried 3 previous kanri versions and both aarch64 and intel architectures... application loads as seen in the activity monitor, however, quickly goes into not responding state. Attached whatever logs made sense to me. Let me know if you require more debug information and how to gather it.

System configuration: Apple M1 Max/32 GB/Ventura 13.5.1 (22G90)

[This is the dump from activity monitor: Sample of kanri.txt](https://github.com/trobonox/kanri/files/12487393/Sample.of.kanri.txt)

<img width="1621" alt="Screenshot 2023-08-31 at 07 50 33" src="https://github.com/trobonox/kanri/assets/9309009/eeafd250-05b2-4f1a-ab9c-b7a6281c4e85">

<img width="539" alt="Screenshot 2023-08-31 at 15 24 46" src="https://github.com/trobonox/kanri/assets/9309009/0ad4dfd2-83c2-459e-bb7a-ea4d59988f41">

**Comment by trobonox** [comment] 2023-08-31 20:20
I apologize for this issue, but fortunately it is one that I have encountered before. It seems to be related to the Tauri plugins I'm using for storage having some kind of memory leak, making a file which saves some persistent storage being very big. The program then tries to load that and essentially keeps doing it infinitely, causing huge ram and storage usage.
The issue is very probably out of my reach since this seems to be some kind of issue with the init logic of the Tauri plugin, most likely only happening as a strange edge case when reinstalling often (that's the only time I've ever encountered this).

The solution is to delete a file generated by Tauri called .persisted-scope
Unfortunately I have only ever encountered this on Windows, where the file was located in the %AppData% folder in a folder called tech.trobo.kanri
Currently I do not have access to my MacBook, but as soon as I do I'm happy to assist if you cannot find the file.

The fix should be deleting the .persisted-scope file (should be a few MB big at this point, usually it should be just a few KB) and possibly reinstalling the app once.

Please let me know if that fixed it and I apologize for the inconvenience.

**Comment by trobonox** [comment] 2023-08-31 20:28
Also when exporting your data, does it take 5 minutes until the save dialog opens or does that open instantly and the actual saving process takes that long?

**Comment by BhaveshDiwan** [comment] 2023-08-31 20:49
Now the application itself its not loading but when it was loading and the performance degradation started happening at that time clicking on "export all data" used to immediately open the OS window to select location of file. On clicking OK, the OS window will close immediately however the data file will be put in place only after roughly 5 mins.
Before this whole degradation started happening, all of it was extremely fast.
Backup file size is only 21Kb and manually verifying JSON has all expected data.

Can you please tell me a list of all directories under which Kanri stores data. I want to delete everything once and try again, if there are any corrupted files causing this.

**Comment by BhaveshDiwan** [comment] 2023-08-31 20:57
Issue fixed, so glad you experienced it before I did and already knew the solution.

Here's the path in mac:
`${HOME}/Library/Application Support/tech.trobonox.kanri/.persisted-scope`

Let's create a troubleshooting section in readme or documentation and list down this issue along with mac and windows paths. When I'll get time to test in Linux, I'll find that path also.

Note: since my data was already backed up, I also deleted `.kanri.dat` so I really cannot comment if that too helped resolve the issue.

**Comment by trobonox** [comment] 2023-08-31 21:03
> Issue fixed, so glad you experienced it before I did and already knew the solution.
> 
> 
> 
> Here's the path in mac:
> 
> `${HOME}/Library/Application Support/tech.trobonox.kanri/.persisted-scope`
> 
> 
> 
> Let's create a troubleshooting section in readme or documentation and list down this issue along with mac and windows paths. When I'll get time to test in Linux, I'll find that path also.
> 
> 
> 
> Note: since my data was already backed up, I also deleted `.kanri.dat` so I really cannot comment if that too helped resolve the issue. 

Creating a troubleshooting section is certainly a good idea, this was a very specific edge case but now that someone else has encountered it before I'm definitely considering documenting the fix for it. Would be great if you could also find the path on Linux.

**Comment by trobonox** [comment] 2023-09-03 08:58
Just added the steps to fix to the troubleshooting section on the new Kanri homepage/docs!
https://www.kanriapp.com/reference/troubleshooting/

Closing this issue since I'd say it's resolved now.
If you find the path on Linux feel free to contribute to the website, it's open source and also on my profile.

**Closed by trobonox** 2023-09-03 08:58 UTC

**Comment by BhaveshDiwan** [comment] 2023-09-09 00:25
@trobonox 
In linux (tested on debian) the path is `${HOME}/.local/share/tech.trobonox.kanri`

Inside I only see `.kanri.dat` and not `.persisted-scope` on a newly launched instance. What conditions trigger creation of this file? I tried making multiple boards, and change theme & wallpapers, and export data. File wasn't created.

**Comment by trobonox** [comment] 2023-09-09 07:29
I believe the `.persisted-scope` file is usually created when you set the background image on a board. I'm not exactly sure but maybe on Linux this file isn't created in the main program folder but in some location with config files such as `${HOME}/.config`.
Thanks for looking into it, will do some investigations of my own as well.
