### ISSUE TITLE
Home Menu Vertical Overflow

### ISSUE THREAD

**Issue by anthonyhfm** [trobonox/kanri#118] opened 2023-03-05 11:18 UTC
While testing Kanri on MacOS it Appeared to me that the Vertical Scroller is always visible in the Home Menu even though there is no overflow. This happens with every Window size.

![image](https://user-images.githubusercontent.com/76816347/222957257-dddee27e-cccd-4139-84ad-0c15423977d0.png)

**Comment by trobonox** [comment] 2023-03-13 20:33
Other users are not able to reproduce this, closing for now

**Closed by trobonox** 2023-03-13 20:33 UTC
Labels: bug
